"""Deterministic rules of the learned parser as served from the repo (learned_parser/, metadata/learned/; spec v1.8 10g). Model-free.

The serving copy is generated by a sync script that once dropped a module constant read only inside a function: the import still
worked and most requests raised NameError. These tests read the served modules and data files directly."""
import ast
import builtins
import importlib
import json
import symtable
from datetime import date
from pathlib import Path

import pytest

from compat.health_range_input import _RANGE
from learned_parser import decode
from learned_parser.decode import Parser, calm, contract_period
from learned_parser.parse import AMBIGUOUS, _months_back, parse_rolling, parse_time_span, resolve_period

ROOT = Path(__file__).resolve().parents[1]
REF = date(2026, 9, 26)  # a Saturday


def span(text):
    got = parse_time_span(text, REF)
    return None if got is None else (got[0].isoformat(), got[1].isoformat())


def sentences(text):
    return [m.group(0).strip() for m in Parser.SENTENCE.finditer(text)]


# ---- the serving copy is complete ----

@pytest.mark.parametrize('module', ['learned_parser.decode', 'learned_parser.parse', 'learned_parser.verify'])
def test_every_module_name_a_function_reads_is_defined(module):
    # A dropped constant that only a function reads (SEPARATORS in Parser.split_run) passes the import and fails per request.
    mod = importlib.import_module(module)
    tables, reads = [symtable.symtable(Path(mod.__file__).read_text(encoding='utf-8'), mod.__file__, 'exec')], set()
    while tables:
        table = tables.pop(); tables += table.get_children()
        if table.get_type() == 'function': reads |= {s.get_name() for s in table.get_symbols() if s.is_global() and s.is_referenced()}
    assert sorted(n for n in reads if n not in vars(mod) and not hasattr(builtins, n)) == []


def test_every_parser_attribute_a_method_reads_is_defined():
    # The same breakage inside the class: a dropped class constant (SENTENCE, INTERNAL, SPAN_MIN, ...) or method.
    tree = ast.parse(Path(decode.__file__).read_text(encoding='utf-8'))
    cls = next(n for n in tree.body if isinstance(n, ast.ClassDef) and n.name == 'Parser')
    attrs = [n for n in ast.walk(cls) if isinstance(n, ast.Attribute) and isinstance(n.value, ast.Name) and n.value.id in ('self', 'cls')]
    stored = {n.attr for n in attrs if isinstance(n.ctx, ast.Store)}
    assert sorted({n.attr for n in attrs if isinstance(n.ctx, ast.Load)} - stored - set(dir(Parser))) == []


def test_the_decoder_reads_the_repo_data():
    # The sync rewrites the experiment decoder's data path; the served word lists are the repo's metadata/learned.
    assert decode.DATA == ROOT / 'metadata' / 'learned'


# ---- shouted text and sentences ----

def test_shouted_text_is_read_in_lowercase_with_the_same_offsets():
    # calm(): case carries no meaning in an all-caps message, but the tagger's character offsets must hold, so a character
    # whose lowercase is two characters ('İ') is kept.
    text = 'WHAT WAS MY HRV IN İSTANBUL LAST WEEK?'
    assert calm(text) == 'what was my hrv in İstanbul last week?' and len(calm(text)) == len(text)


@pytest.mark.parametrize('text', ["What's my HRV, RHR and LDL today?", 'HRV?', 'LDL/HDL', 'SHOW HRV'])
def test_mixed_case_and_short_text_are_unchanged(text):
    # Acronyms inside a normal sentence are not shouting; under 8 letters is too short to tell.
    assert calm(text) == text


@pytest.mark.parametrize('text', ['I got a Whoop 4.0 last month', 'My fasting glucose was 5.6 mmol this morning'])
def test_a_decimal_point_does_not_end_a_sentence(text):
    # Spec v1.8 10g.28 plans only the sentences that carry the read, so "Whoop 4.0" must not split into "Whoop 4." and "0 ...".
    assert sentences(text) == [text]


@pytest.mark.parametrize('text,expected', [
    ('Great run. Show my steps', ['Great run.', 'Show my steps']),
    ('Should I buy a Whoop? What is my HRV?', ['Should I buy a Whoop?', 'What is my HRV?']),
    ('Great run! Show my steps', ['Great run!', 'Show my steps']),
    ('Show my HRV; and my steps', ['Show my HRV;', 'and my steps']),
    ('I got a Whoop 4.0. What is my HRV?', ['I got a Whoop 4.0.', 'What is my HRV?']),
])
def test_a_stop_before_a_space_ends_a_sentence(text, expected):
    assert sentences(text) == expected


# ---- food intake (spec v1.8 10g.30) ----

@pytest.mark.parametrize('text', ['grams of protein yesterday', '120g of protein today', 'How much caffeine did I have today?',
                                  "calories I've had today", 'calories I logged this week', 'net calories this week', 'calories in vs out'])
def test_intake_wording(text):
    # Nutrient grams, "how much <nutrient>", calories with had/logged, net calories and "calories in" are intake -> handoff.
    assert Parser._intake(text)


@pytest.mark.parametrize('text', ['How many active calories did I have yesterday?', 'calories today', 'calories in my workout yesterday',
                                  'Do I have any food allergies in my labs?', 'How much total protein is in my blood panel?', 'how much fat do I have'])
def test_burn_workout_lab_and_body_wording_is_not_intake(text):
    # A burn word vetoes "had"; "calories today" is calories_burned and "calories in my workout" workout_calories; not_intake
    # phrases (food allergies, total protein) are removed first. 10g.32 item 7: "how much fat do I have" is fat_mass.
    assert not Parser._intake(text)


# ---- contract periods ----

@pytest.mark.parametrize('period,expected', [
    ({'kind': 'relative', 'amount': 3, 'unit': 'weeks'}, {'kind': 'relative', 'amount': 21, 'unit': 'days'}),
    ({'kind': 'relative', 'amount': '2', 'unit': 'weeks'}, {'kind': 'relative', 'amount': 14, 'unit': 'days'}),
    ({'kind': 'calendar', 'period': 'year'}, {'kind': 'between', 'start_at': '2026-01-01', 'end_at': '2026-09-26'}),
])
def test_weeks_and_the_calendar_year_become_contract_shapes(period, expected):
    # The contract has neither (compat/health_range_input.py): N weeks is 7N days; the current year is year to date (spec item 10).
    assert contract_period(period, REF) == expected


@pytest.mark.parametrize('period', [{'kind': 'relative', 'amount': 30, 'unit': 'days'}, {'kind': 'relative', 'amount': 6, 'unit': 'months'},
                                    {'kind': 'calendar', 'period': 'day'}, {'kind': 'calendar', 'period': 'week'}, {'kind': 'calendar', 'period': 'month'},
                                    {'kind': 'between', 'start_at': '2026-08-01', 'end_at': '2026-08-31'}, {'kind': 'all_history'}])
def test_contract_shapes_pass_unchanged(period):
    assert contract_period(period, REF) == period


def test_every_resolved_period_passes_the_plan_contract():
    # Each shape resolve_period emits, after contract_period, is one HealthRead accepts (query_plan validates with _RANGE).
    for kind in ('rolling', 'calendar', 'to_date', 'night'):
        for unit in ('day', 'week', 'month', 'year'):
            for offset in (None, 'current', 'previous'):
                period = resolve_period(kind, 2, unit, offset, REF); period.pop('night', None)
                _RANGE.validate_python(contract_period(period, REF))


def test_only_the_outer_plan_is_rewritten():
    # Parser.select: re-entrant calls (prior turn, clauses) keep the decoder's shapes for follow-up arithmetic; research has no period.
    parser = Parser.__new__(Parser)       # no model: _select is replaced
    plan = {'status': 'planned', 'reason_codes': [], 'queries': [
        {'kind': 'health', 'metrics': ['steps'], 'period': {'kind': 'relative', 'amount': 2, 'unit': 'weeks'}}, {'kind': 'research', 'topic': 'zone-2 training'}]}
    parser._select = lambda req: plan
    req = {'state': {'reference_date': '2026-09-26'}}
    assert parser.select(req)['queries'] == [{**plan['queries'][0], 'period': {'kind': 'relative', 'amount': 14, 'unit': 'days'}}, plan['queries'][1]]
    assert parser.select({**req, '_clause': True}) is plan


# ---- 'since <event>' anchors (spec v1.8 10g.29, 10g.31, 10g.32 item 4) ----

def test_since_anchor_data_has_every_list_the_decoder_reads():
    # The lists are data (since_anchors.json); an empty one silently switches its rule off.
    data = json.loads((decode.DATA / 'since_anchors.json').read_text(encoding='utf-8'))
    keys = ('medical', 'account_start', 'restart', 'device_start_verbs', 'back_reference', 'data_start', 'replacement', 'device_version', 'lab_sources')
    assert [k for k in keys if not data.get(k)] == []
    assert {'quest', 'labcorp'} <= set(data['lab_sources']) and not {'quest', 'labcorp'} & set(decode.SA_DEVICES.values())   # labs start no device series


@pytest.mark.parametrize('rx,event', [('SA_REPLACE', 'I got my new Oura'), ('SA_REPLACE', 'I upgraded my Whoop'),
                                      ('SA_VERSION', 'I got my Oura Ring 4'), ('SA_VERSION', 'I got my Whoop 4.0')])
def test_same_brand_replacement_is_marked(rx, event):
    # 10g.32 item 4 (amended): the old unit's data carries the same source id, so a replacement or a model/version hands off.
    assert getattr(decode, rx).search(event)


@pytest.mark.parametrize('event', ['I got my Oura', 'I started wearing my Whoop', 'I renewed my Garmin plan'])
def test_a_first_device_is_not_a_replacement(event):
    assert not (decode.SA_REPLACE.search(event) or decode.SA_VERSION.search(event))


@pytest.mark.parametrize('event,starts', [('I got my Oura', True), ('I bought a Whoop', True), ('I started wearing my Garmin', True), ('I switched to Whoop', True),
                                          ('I connected my Oura', False), ('I synced my Whoop', False), ('I paired my Garmin', False), ('I linked my Fitbit', False)])
def test_device_start_verbs(event, starts):
    # 10g.32 item 4: wearing, switching and acquisition verbs start a device's series; integration verbs do not (backfills predate them).
    assert bool(decode.SA_DEVICE_VERB.search(event)) is starts


@pytest.mark.parametrize('text,expected', [
    ('HRV since I got my Oura', (None, ('device', 'oura'))),                        # 10g.32 item 4: an acquisition verb
    ('recovery since I switched to Whoop', (None, ('device', 'whoop'))),            # 10g.31: device start
    ('LDL since I started tracking', (None, ('data',))),                           # 10g.31: data start
    ('Ferritin since my first blood test', (None, ('data',))),                    # 10g.31: "my first reading/test", a blood or lab test too
    ('HRV since I switched to Whoop in June', (None, None)),                       # 10g.29: a date binds the window instead
    ('HRV since I connected my Oura', ('unresolved_temporal_phrase', None)),        # 10g.32 item 4: an integration verb
    ('HRV since I got my new Oura', ('unresolved_temporal_phrase', None)),          # 10g.32 item 4: same-brand replacement
    ('HRV since I got my Whoop 4.0', ('unresolved_temporal_phrase', None)),
    ('HRV since I started using the app', ('unresolved_temporal_phrase', None)),    # 10g.31: account start
    ('HRV since I started wearing it again', ('unresolved_temporal_phrase', None)),   # 10g.31: a restart
    ('HRV since I started Ozempic', ('unresolved_temporal_phrase', None)),          # 10g.29: an event with no date
    ('HRV since I started Ozempic in May', ('unbound_request_constraint', None)),    # 10g.29: medical context hands off even with a date
])
def test_since_event_anchors(text, expected):
    parser = Parser.__new__(Parser)       # no model: the rule reads the text, the read's own mention and the data lists
    reading = [m.span() for m in Parser.SENTENCE.finditer(text)]
    assert parser._since(text, REF, reading, runs=[(0, text.index(' '))]) == expected


# ---- sources (spec v1.8 10g.5) ----

@pytest.mark.parametrize('text,hit', [('my Strava distance', True), ('HRV from my Galaxy Watch', True), ('my Garmin distance', False), ('my Apple Watch steps', False)])
def test_brands_vita_does_not_ingest(text, hit):
    # 10g.32 item 6: naming one leaves a source that cannot be bound (unbound_source), even when the tagger does not mark it.
    assert bool(decode.NOT_INGESTED.search(text)) is hit


def test_everyday_word_aliases_bind_only_where_tagged():
    # "quest" and "polar" are everyday words: they bind only where the tagger marks a source. Brand names bind from the text.
    assert {'quest', 'polar'} <= decode.COMMON_ALIASES <= set(decode.SOURCE_ALIASES)
    assert not decode.COMMON_ALIASES & {'garmin', 'oura', 'whoop', 'fitbit', 'withings'}


# ---- recency words (spec v1.8 10g.13, 10g.32 items 1 and 9) ----

@pytest.mark.parametrize('name,hits,misses', [
    ('VAGUE_RECENCY', ["how's my sleep lately", 'recently', 'these days', 'of late', 'nowadays'], ['my most recent HRV', 'last week', 'I slept late']),   # no window
    ('BUNDLE_LATEST', ['latest sleep quality', 'my most recent sleep', 'newest'], ['my sleep lately', 'last night', 'my sleep now']),   # bundle: last night
    ('BUNDLE_STATE', ['right now', 'my sleep now', 'currently', 'at the moment', 'these days', 'nowadays'], ['lately', 'recently', 'I know my sleep', 'latest']),   # 30-day trend
    ('STATE_DAYS', ['Where is my ApoB at these days?', 'nowadays', 'my ferritin lately', 'recently', 'of late'], ['now', 'currently', 'right now']),   # period words (10g.32 item 9): latest if sparse, trend if daily
])
def test_recency_words(name, hits, misses):
    rx = getattr(decode, name)
    assert [t for t in hits if not rx.search(t)] == [] and [t for t in misses if rx.search(t)] == []


# ---- analyte groups (spec v1.8 10g.1, 10g.27) ----

def test_bare_glucose_reads_both_sampling_ids_and_fasting_glucose_stays_specific():
    # 10g.27: bare "glucose" reads every present id of {glucose, fasting_glucose}; the two link views compare them as one analyte.
    assert decode.UNIT_SPLIT['glucose'] == {'glucose', 'fasting_glucose'} and 'fasting_glucose' not in decode.UNIT_SPLIT
    assert decode.ANALYTE['glucose'] == decode.ANALYTE['fasting_glucose']


def test_unit_variants_expand_only_from_the_legacy_id():
    # 10g.1: bare "neutrophils" reads every unit variant; "neutrophil %" and "ANC" stay specific.
    assert decode.UNIT_SPLIT['neutrophils'] == {'neutrophils', 'neutrophils_percent', 'neutrophils_absolute'}
    assert not {'neutrophils_percent', 'neutrophils_absolute'} & set(decode.UNIT_SPLIT)


def test_glucose_and_fasting_glucose_are_not_spelling_variants():
    # 10g.27: in one spelling group "fasting glucose" would read glucose too. A true spelling group still reads every id (10g.1).
    assert 'fasting_glucose' not in decode.SPELLING.get('glucose', set()) and 'glucose' not in decode.SPELLING.get('fasting_glucose', set())
    assert decode.SPELLING['lp_a'] == {'lipoprotein_a', 'lp_a', 'lpa'}


def test_catalog_ambiguous_names_are_loaded():
    # parse.py falls back to an empty set when vocabulary_ambiguous.json is missing, which would plan a bare "CRP" silently.
    # Spec 10e: CRP, calcium; v1.7 10f: magnesium, temperature/temp -> ambiguous_metric_alias.
    assert {'crp', 'calcium', 'magnesium', 'temperature', 'temp'} <= AMBIGUOUS


# ---- date functions of learned_parser.parse not covered by test_learned_dates.py ----

@pytest.mark.parametrize('text,expected', [
    ('past 30 days', (30, 'day')), ('last 8 weeks', (8, 'week')), ('the past week', (1, 'week')), ('over the last week', (1, 'week')),
    ('in the last month', (1, 'month')), ('last two months', (2, 'month')), ('last couple of weeks', (2, 'week')),
    ('last week', None), ('last year', None), ('this week', None),
])
def test_rolling_windows_versus_calendar_periods(text, expected):
    # Spec v1.8 10g.3: "(the) past X" and "over/in/during/within the last X" are rolling; bare "last X" is the calendar X.
    assert parse_rolling(text) == expected


@pytest.mark.parametrize('args,expected', [
    (('rolling', 36, 'day', None, REF, 'past 90 days'), {'kind': 'relative', 'amount': 90, 'unit': 'days'}),   # the stated number beats the capped head
    (('rolling', 2, 'year', None, REF), {'kind': 'relative', 'amount': 24, 'unit': 'months'}),
    (('calendar', 0, 'week', 'previous', REF), {'kind': 'between', 'start_at': '2026-09-14', 'end_at': '2026-09-20'}),   # 10g.3: bare "last week"
    (('calendar', 0, 'month', 'previous', REF), {'kind': 'between', 'start_at': '2026-08-01', 'end_at': '2026-08-31'}),
    (('calendar', 0, 'year', 'previous', REF), {'kind': 'between', 'start_at': '2025-01-01', 'end_at': '2025-12-31'}),
    (('calendar', 0, 'month', 'current', REF), {'kind': 'calendar', 'period': 'month'}),
    (('since', 0, None, None, REF, 'since June', parse_time_span), {'kind': 'between', 'start_at': '2026-06-01', 'end_at': '2026-09-26'}),
    (('night', 0, None, None, REF), {'kind': 'between', 'start_at': '2026-09-26', 'end_at': '2026-09-26', 'night': True}),   # 10g.4: last night
])
def test_resolve_period(args, expected):
    assert resolve_period(*args) == expected


@pytest.mark.parametrize('args', [('rolling', 0, 'day', None, REF), ('between', 0, None, None, REF, 'next week', parse_time_span),
                                  ('day', 0, None, None, REF, None, parse_time_span)])
def test_unresolvable_periods_are_none(args):
    # No amount, a future window (10g.3: metrics cannot read the future) or no date text: None, which the decoder hands off.
    assert resolve_period(*args) is None


@pytest.mark.parametrize('day,months,expected', [(date(2026, 3, 31), 1, date(2026, 2, 28)), (date(2024, 3, 31), 1, date(2024, 2, 29)),
                                                 (date(2026, 1, 15), 2, date(2025, 11, 15)), (date(2026, 9, 26), 12, date(2025, 9, 26)),
                                                 (date(2026, 9, 26), -4, date(2027, 1, 26))])
def test_month_arithmetic_clamps_the_day(day, months, expected):
    # Spec v1.8 10g.24: Vita's month arithmetic, same day of month, clamped.
    assert _months_back(day, months) == expected


@pytest.mark.parametrize('text,expected', [
    ('on Tuesday', ('2026-09-22', '2026-09-22')),          # 10g.3: the most recent such day strictly before the reference date
    ('on Saturday', ('2026-09-19', '2026-09-19')),         # asked on a Saturday: 7 days back
    ('Tuesday last week', ('2026-09-15', '2026-09-15')),
    ('this Sunday', ('2026-09-27', '2026-09-27')),         # still ahead this week: future, which the caller hands off
    ('last weekend', ('2026-09-19', '2026-09-20')),        # the most recent complete Sat-Sun
    ('this weekend', ('2026-09-26', '2026-09-26')),        # Saturday of this week -> now
    ('the week before last', ('2026-09-07', '2026-09-13')),
    ('the day before yesterday', ('2026-09-24', '2026-09-24')),
    ('3 days ago', ('2026-09-23', '2026-09-23')),          # 10g.24: that day
    ('this week', ('2026-09-21', '2026-09-26')),           # item 10: the current period to date
    ('last night', ('2026-09-26', '2026-09-26')),          # 10g.4: the night ending on the reference date
    ('yesterday night', ('2026-09-26', '2026-09-26')),     # 10g.4: "<D> night" started on D, so this is last night
    ('Tuesday night', ('2026-09-23', '2026-09-23')),
])
def test_relative_day_phrases(text, expected):
    assert span(text) == expected


@pytest.mark.parametrize('text,expected', [('yestrday', ('2026-09-25', '2026-09-25')), ('on wendesday', ('2026-09-23', '2026-09-23')),
                                           ('last weekedn', ('2026-09-19', '2026-09-20')), ('on mondays', None), ('on weekends', None),
                                           ('toady', None), ('sundae', None)])
def test_misspelled_day_words(text, expected):
    # parse._fix_typo: a misspelled day word reads as that word; "today" and "sunday" are exact-only ("toady", "sundae"), and
    # plural weekdays or weekends are recurring filters, never one day.
    assert span(text) == expected


# ---- period gaps found on the v11 dev set (coverage11b; spec v1.8 10d, 10g.3, 10g.15, 10g.24-10g.26) ----

@pytest.mark.parametrize('text,expected', [
    ('rhr yday', ('2026-09-25', '2026-09-25')),                                 # 10d: "yday" is yesterday
    ('sws last nite', ('2026-09-26', '2026-09-26')),                            # 10g.4: "last nite" is last night
    ('Step data from September of last year', ('2025-09-01', '2025-09-30')),    # 10g.3: a year as stated; bare "last year" = 2025
    ('steps in March last year', ('2025-03-01', '2025-03-31')),
    ('steps September 3 last year', ('2025-09-03', '2025-09-03')),
    ('steps in June of this year', ('2026-06-01', '2026-06-30')),
])
def test_short_day_forms_and_a_month_of_last_year(text, expected):
    assert span(text) == expected


def test_a_later_month_of_this_year_is_future():
    assert span('VO2 max for December of this year')[0] == '2026-12-01'     # the caller hands off a window that starts after today


@pytest.mark.parametrize('text,unit', [('rhr 3 wks ago', 'week'), ('HRV 2 mos ago', 'month'), ('weight 1 yr ago', 'year'), ('steps 3 weeks ago', 'week')])
def test_unit_abbreviations_name_the_unit_of_n_units_ago(text, unit):
    # 10g.24: "3 wks ago" is the point 3 weeks back, read as "3 weeks ago".
    m = decode.UNITS_AGO_ANY.search(text)
    assert m and decode.UNIT_ABBR.get(m.group(3).lower(), m.group(3).lower()) == unit


@pytest.mark.parametrize('text,hit', [('and the year prior?', True), ('and the week prior to that one?', True), ('and the week preceding that?', True),
                                      ('and the day preceding it?', True), ('the day before yesterday', False), ('the week before last', False)])
def test_the_unit_prior_or_preceding_is_the_unit_before(text, hit):
    # 10g.25: relative-to-prior words; "the <unit> before yesterday/last" is an absolute date.
    assert bool(decode.PREV_UNIT.search(text)) is hit


@pytest.mark.parametrize('text', ['the year before?', 'and the year prior?'])
def test_the_year_before_re_anchors_the_prior_window(text):
    # 10g.25: "the year before?" after a window shorter than a year is that window in the previous year (year re-anchoring).
    assert decode.YEAR_REANCHOR.search(text)


@pytest.mark.parametrize('text,standalone', [
    ('What did my hs-CRP come back as?', True), ('What did I weigh?', True), ('What VO2 max am I at now?', True),
    ('What readiness score do I have?', True),                                   # 10g.26: complete questions with their own predicate
    ('what did it say for yesterday?', False), ('what about my RHR?', False),   # a pronoun, a connector form
    ('what does the literature say about it?', False)])
def test_complete_questions_stand_alone(text, standalone):
    assert decode.self_contained(text) is standalone


@pytest.mark.parametrize('text,unit', [('deep sleep on that same day?', 'day'), ('what was my distance over the same days?', 'days'),
                                       ('active calories for that week?', 'week'), ('and my stress during that period?', 'period'),
                                       ('what was my weight then?', None)])
def test_back_reference_windows(text, unit):
    # 10g.26 (c): an explicit back-reference to the prior window, and the unit it names.
    m = decode.BACKREF_WINDOW.search(text)
    assert m and m.group(1) == unit


@pytest.mark.parametrize('text', ['this week', 'the week before', 'last week', 'on Tuesday'])
def test_standalone_windows_are_not_back_references(text):
    assert not decode.BACKREF_WINDOW.search(text)


@pytest.mark.parametrize('unit,period,fits', [
    ('day', {'kind': 'between', 'start_at': '2026-09-25', 'end_at': '2026-09-25'}, True),
    ('day', {'kind': 'between', 'start_at': '2026-09-14', 'end_at': '2026-09-20'}, False),      # "that day" after a week: which day?
    ('week', {'kind': 'between', 'start_at': '2026-09-14', 'end_at': '2026-09-20'}, True),
    ('week', {'kind': 'calendar', 'period': 'week'}, True),
    ('week', {'kind': 'between', 'start_at': '2026-09-22', 'end_at': '2026-09-22'}, False),     # "that week" after a day
    ('weekend', {'kind': 'between', 'start_at': '2026-09-19', 'end_at': '2026-09-20'}, True),
    ('month', {'kind': 'between', 'start_at': '2026-08-01', 'end_at': '2026-08-31'}, True),
    ('month', {'kind': 'relative', 'amount': 30, 'unit': 'days'}, False),
    ('year', {'kind': 'between', 'start_at': '2025-01-01', 'end_at': '2025-12-31'}, True),
    ('days', {'kind': 'relative', 'amount': 3, 'unit': 'months'}, True),                         # plural and generic words fit any window
    (None, {'kind': 'calendar', 'period': 'month'}, True)])
def test_a_back_reference_unit_must_fit_the_prior_window(unit, period, fits):
    assert decode.window_fits(unit, period, REF) is fits


@pytest.mark.parametrize('text,scope', [('across the whole day', True), ('the entire day', True), ('this week', False), ('each day', False)])
def test_the_scope_of_a_named_day_is_no_window_of_its_own(text, scope):
    # "Yesterday's average heart rate across the whole day": one window (10g.6 counts windows).
    assert bool(decode.WHOLE_DAY.fullmatch(text)) is scope


def test_most_recently_is_a_latest_word_and_no_window():
    # 10g.15: explicit latest words win; "Which workout did I do most recently?" states no window.
    assert decode.LATEST_OP.search('How much deep sleep did I get most recently?') and decode.MOST_RECENTLY.search('which workout did I do most recently')
    assert not decode.MOST_RECENTLY.search('my most recent HRV')


@pytest.mark.parametrize('text,when,event', [
    ('My half marathon was on the 14th.', 'on the 14th', True), ('We moved house in August.', 'in August', True),
    ("It's my birthday today!", 'today', True), ('Two weeks ago I got a new ring.', 'Two weeks ago', True),
    ('Last week please.', 'Last week', False), ('Only for this week.', 'this week', False), ('Say, over the last two weeks.', 'over the last two weeks', False),
    ('I want to see it for the past month.', 'the past month', False), ('Can you do last week?', 'last week', False),
    ('Make it the last 14 days.', 'the last 14 days', False), ('It was last Sunday I think.', 'last Sunday', False),
    ('Last week was stressful at work.', 'Last week', False)])      # no first-person subject: the date still binds the read, as before
def test_a_side_sentence_states_a_dated_event_only_in_the_first_person_asking_nothing(text, when, event):
    # 10g.28 (clarified): a dated event in a context sentence is plain context; a window, request or correction sentence is the read's.
    a = text.index(when)
    assert decode.side_event(text, [(a, a + len(when))]) is event


@pytest.mark.parametrize('text,present', [("What's my resting heart rate?", True), ('How is my HRV', True), ('my weight now', True),
                                          ('What was my HRV?', False), ('How did I sleep?', False), ('Show my glucose.', False)])
def test_a_read_without_its_own_window_asks_for_a_present_value(text, present):
    # A read with no window next to a dated event is re-read alone only for a present value; a past or open read may mean the event's date.
    assert bool(decode.PRESENT_READ.search(text)) is present


@pytest.mark.parametrize('text', ['What was my HRV that day?', 'steps during the trip?', 'how has it changed since then?', 'my RHR the day after'])
def test_reads_that_refer_back_to_a_side_event(text):
    assert decode.CTX_BACKREF.search(text)


@pytest.mark.parametrize('before,when,after,start', [
    ('My weight starting ', 'from January', '', 'January'), ('Show my weight ', 'starting in January', '', 'January'),
    ('Show my sleep score going back to ', 'March', '', 'March'), ('HRV from ', 'March', ' onwards', 'March'), ('HRV from ', 'March', ' on', 'March'),
    ('steps from ', 'June', ' to date', 'June'), ('weight ', 'beginning in January', '', 'January'),
    ('resting heart rate from the start of ', 'August', '', 'August'), ('steps for ', 'June onwards', '', 'June'), ('HRV ', 'since last week', '', 'last week'),
    ('HRV from ', 'January', '', None), ('my sleep from ', 'last night', '', None), ('HRV ', 'from January to March', '', None),
    ('HRV ', 'this month', ' to date', None), ('steps ', 'since 3 weeks ago', '', None), ('steps from ', 'Monday', ' on my watch', None),
    ('HRV at the beginning of ', 'the month', '', None), ('steps over ', 'the last 3 months', ' up to today', None), ('steps ', 'to date', '', None),
    ("I'd like to see my steps going back to ", 'March', '', 'March'), ('weight ', 'dating back to January', '', 'January'),
    ('', 'go back to June', '', None), ('', 'back to June', '', None), ('Going back to ', 'March', ', what was my weight?', None)])   # a return to X
def test_open_ended_starts_read_from_their_date(before, when, after, start):
    # 10g.35 item 3 reads "since <period>" from its start to now; "starting in", "going back to", "onwards" and "to date" say the same.
    # A bare "from X" is X's own window ("my sleep from last night"); a range, the current period and "N units ago" stay as they are.
    assert decode.open_start(before, when, after) == start


@pytest.mark.parametrize('text,expected', [
    ('Hey, respiratory rate this month', 'respiratory rate this month'), ("What's my RBC count? Thanks!", "What's my RBC count?"),
    ('rhr  last  wk', 'rhr last wk'), ('Quick question: what height is saved in my profile?', 'what height is saved in my profile?'),
    ('Show my weight trend pls 🙏🙏', 'Show my weight trend'), ('Hello there, steps today', 'steps today'),
    ('so far today, how many steps?', 'so far today, how many steps?'), ('😴 REM last night', '😴 REM last night'),
    ('Please show my steps', 'Please show my steps'), ('Hip circumference', 'Hip circumference'), ('thanks', 'thanks'), ('Hi!', 'Hi!')])
def test_the_model_reads_a_request_without_pleasantries_or_runs_of_spaces(text, expected):
    # Stress set s2: the same requests planned without "Hey,", "Thanks!", an emoji or double spaces; "so far" and a leading emoji stay.
    assert decode.plain(text) == expected


@pytest.mark.parametrize('side,when,read,expected', [
    ('My half marathon was on the 14th.', 'on the 14th', 'What was my HRV that day?', 'What was my HRV on 2026-09-14?'),
    ('My half marathon was on the 14th.', 'on the 14th', 'What was my HRV the day before?', 'What was my HRV on 2026-09-13?'),
    ('I moved to Berlin in March.', 'in March', 'How has my resting heart rate changed since then?', 'How has my resting heart rate changed since 2026-03-01?'),
    ('I was in Lisbon from the 3rd to the 9th.', 'from the 3rd to the 9th', 'How many steps during the trip?', 'How many steps from 2026-09-03 to 2026-09-09?'),
    ('I did a charity swim in July.', 'in July', 'What was my HRV that day?', None),         # a month names no one day
    ('I flew to Crete on the 3rd.', 'on the 3rd', 'Steps during the holiday?', None),           # the trip's end is not stated
    ('My half marathon was on the 14th.', 'on the 14th', 'What was my HRV then?', None)])      # "then" is unclear
def test_a_read_referring_back_to_a_side_event_takes_the_event_date(side, when, read, expected):
    # 10g.28 (clarified): "...What was my HRV that day?" -> the event's day; "...steps during the trip?" -> the trip's dates.
    cur = side + ' ' + read; a = cur.index(when)
    assert Parser._bind_event(read, decode.CTX_BACKREF.search(read), cur, [(0, len(side))], [(a, a + len(when))], REF) == expected


@pytest.mark.parametrize('text,expected', [('lst wk', ('2026-09-14', '2026-09-20')), ('restng hr lst wk', ('2026-09-14', '2026-09-20')),
                                           ('this wk', ('2026-09-21', '2026-09-26')), ('lst yr', ('2025-01-01', '2025-12-31')),
                                           ('last wknd', ('2026-09-19', '2026-09-20')), ('prev week', ('2026-09-14', '2026-09-20')),
                                           ('hr last week', ('2026-09-14', '2026-09-20')), ('mo farah steps', None)])
def test_clipped_period_words_read_as_the_full_words(text, expected):
    # v11-1038 "restng hr lst wk": unread, the date syntax could not check an offset head that read this week; "hr" stays heart rate.
    assert span(text) == expected


def test_clipped_rolling_windows():
    assert parse_rolling('past 2 wks') == (2, 'week') and parse_rolling('last 3 mos') == (3, 'month')


@pytest.mark.parametrize('text,bound', [('Steps in September after the 15th.', True), ('so um show hrv from last month before the 10th', True),
                                        ('HRV before Sep 10', True), ('steps after 3 September', True), ('sleep prior to Tuesday', True),
                                        ('What was my HRV the day before?', False), ('the day before yesterday', False), ('the week before last', False),
                                        ('HRV after my run', False), ('steps since the 15th', False), ('HRV before sunrise', False)])
def test_a_date_bound_inside_the_read_is_a_filter(text, bound):
    # v12-0232, v12-1385 (10g.28 class 4: "before/after <date>" applied to the readings) hand off; relative days and "since" do not.
    assert bool(decode.DATE_BOUND.search(text)) is bound


@pytest.mark.parametrize('text,later', [('Active calories later this week', True), ('steps for the rest of the day', True),
                                        ('the remainder of this month', True), ('HRV later that day', False)])
def test_the_rest_of_a_current_period_is_future(text, later):
    assert bool(decode.LATER.search(text)) is later       # v12-0345


@pytest.mark.parametrize('text,display', [('show my steps', True), ('Show me HRV', True), ('showing my weight trend', True),
                                          ('What did my last ferritin test show?', False), ('What did my last LDL test show? ✨', False), ('what does it show', False)])
def test_show_as_a_result_verb_is_no_display_request(text, display):
    assert bool(decode.SHOW_VERBS.search(text)) is display     # v12-0666, v12-1092: "what did my last X test show?" asks for the latest value


@pytest.mark.parametrize('text,typical', [("hmm what's my usual resting heart rate", True), ("What's my typical daily distance?", True),
                                          ('how many steps do I usually get', True), ('Is my HRV unusual?', False)])
def test_usual_and_typical_name_the_typical_value(text, typical):
    assert bool(decode.TYPICAL_DAY.search(text)) is typical    # v12-1040, v12-1242 (10g.33 item 4): trend over the default window


@pytest.mark.parametrize('text,expected', [('on 13.08.2026.', ('2026-08-13', '2026-08-13')), ('the night of september 14', ('2026-09-15', '2026-09-15')),
                                           ('Thursday last wek', ('2026-09-17', '2026-09-17')), ('Mon-Wed', ('2026-09-21', '2026-09-23')),
                                           ('the 3rd to the 9th', ('2026-09-03', '2026-09-09')), ('Sept 3-9', ('2026-09-03', '2026-09-09')),
                                           ('the week preceding last week', ('2026-09-07', '2026-09-13'))])
def test_v13_date_forms(text, expected):
    # A dotted date before a full stop, the night of a date (10g.4: it ends the next day), "wek", weekday and day-of-month ranges.
    assert span(text) == expected


@pytest.mark.parametrize('text,expected', [('last sixty days', (60, 'day')), ('past forty-five days', (45, 'day')), ('last twenty one days', (21, 'day'))])
def test_number_words_above_twelve(text, expected):
    assert parse_rolling(text) == expected       # v13-0404 "strain over the last sixty days" was read as 30 days


def test_an_impossible_iso_date_is_invalid():
    from learned_parser.parse import InvalidDate
    with pytest.raises(InvalidDate):
        parse_time_span('2026-13-01', REF)


@pytest.mark.parametrize('text,unread', [('the last sixty days', True), ('over the last 45 days', True), ('the past week', False), ('this month', False)])
def test_an_explicit_count_is_spotted(text, unread):
    assert bool(decode.SPOKEN_N.search(text)) is unread   # the decoder hands off when the parser cannot read such a count


@pytest.mark.parametrize('text,narrow', [('Bdy comp: just muscle mass', True), ('Lipids - only LDL', True), ('show my steps', False), ('HRV: last week', False)])
def test_a_label_narrowed_to_a_member(text, narrow):
    assert bool(decode.NARROW_TEXT.match(text)) is narrow  # v13-1205: a misspelt panel name still narrows (10g.34 item 4)


def test_thanks_in_advance_is_a_pleasantry():
    assert decode.plain('How is my ApoB lately? Thanks in advance!') == 'How is my ApoB lately?'
